### PR TITLE
#58 fix improve unit test

### PR DESCRIPTION
**Pull request by YULEMING**
This should be a buildable version.
Fixed: unit test_dispenser.c
Added: unit test_limitSwitch.c, test_hardwareHelper.c

### CODE REVIEW

**Comment by DavidFederl** [comment]
I'am not able to build the unit test for the dispenser and the limit switch!

**Comment by YULEMING** [comment]
> I'am not able to build the unit test for the dispenser and the limit switch!

Do you have a CMake configuration `unit-test`? Could you share your CMake configuration of Embedded Controller part. I'm not sure does it matter or not.
I build these unit tests using `-DDEBUG:BOOL=ON -DUNIT_TEST:BOOL=ON` and the build type is `unit-test`.
I'm using CLion and I have:
* debug
  build type: debug
  CMake options: -DDEBUG:BOOL=ON -DUNIT_TEST:BOOL=OFF
* release
  build type: release
  CMake options: -DDEBUG:BOOL=OFF -DUNIT_TEST:BOOL=OFF
* unit-test
  build type: unit-test
  CMake options: -DDEBUG:BOOL=ON -DUNIT_TEST:BOOL=ON

**Comment by DavidFederl** [comment]
> > I'am not able to build the unit test for the dispenser and the limit switch!
> 
> Do you have a CMake configuration `unit-test`? Could you share your CMake configuration of Embedded Controller part. I'm not sure does it matter or not. I build these unit tests using `-DDEBUG:BOOL=ON -DUNIT_TEST:BOOL=ON` and the build type is `unit-test`. I'm using CLion and I have:
> 
> * debug
>   build type: debug
>   CMake options: -DDEBUG:BOOL=ON -DUNIT_TEST:BOOL=OFF
> * release
>   build type: release
>   CMake options: -DDEBUG:BOOL=OFF -DUNIT_TEST:BOOL=OFF
> * unit-test
>   build type: unit-test
>   CMake options: -DDEBUG:BOOL=ON -DUNIT_TEST:BOOL=ON
> 
> I tried on my another laptop by checkout to this branch, the build was failed. I will fix it.

The unit test configuration is already defined in the CMake. It can be invoked by running
```bash
# create build files
cmake -B build/unit-tests -G Ninja -D CMAKE_BUILD_TYPE=DEBUG -D UNIT_TEST:BOOL=ON -D DEBUG:BOOL=ON

# run build
cmake --build build/unit-tests -j 4 --clean-first

# run unit tests
ctest --test-dir build/Unittest/test/unit/ --output-on-failure
```

> If you replace the `-D UNIT_TEST:BOOL=ON` with `-D UNIT_TEST_BOOL=OFF` you would build the targets for the Tiny2040.
> This is due to the fact, that the unit tests for local execution can't contain the pico-sdk!

---

The output I receive when trying to build the test is, that there is a problem with linkage of other libraries.

**Comment by YULEMING** [comment]
It's fixed in the latest commit. I built the project with my two laptops, they are both working. The problem is caused by variables declared in the header files. The header files are included multiple times. Because the variables are only used in one .c file, I moved them to their corresponding .c files.

**Review by DavidFederl — APPROVED** [review]

**Pull request merged**
