### PR TITLE
Refactoring the code

### PR DESCRIPTION
**Pull request by HuangQing23**
refactoring the libraries

### CODE REVIEW

**Comment by HuangQing23** [comment]
> Please do a merge into the develop branch and not directly into main.
> 
> Does the build of the Project work for you? When I am building the project I am getting a lot of "unknown type name" errors and other warnings.

OK got it. It do works for me, but it seems like it doesn't work for you and Renhong. I'll pull the new thing later. I just got some computer problems.

**Comment by HuangQing23** [comment]
> Most of the errors are in the motor.h:
> 
> D:/CLionProjects/SIGMA_Embedded/src/motor/motor.h:51:18: error: unknown type name 'dispenser_t' 51 | void motorDoStep(dispenser_t *dispenser); | ^~~~~~~~~~~ D:/CLionProjects/SIGMA_Embedded/src/motor/motor.h:57:8: error: unknown type name 'dispenserState_t' 57 | static dispenserState_t sleepState(dispenser_t *dispenser); | ^~~~~~~~~~~~~~~~ D:/CLionProjects/SIGMA_Embedded/src/motor/motor.h:57:36: error: unknown type name 'dispenser_t' 57 | static dispenserState_t sleepState(dispenser_t *dispenser); | ^~~~~~~~~~~ D:/CLionProjects/SIGMA_Embedded/src/motor/motor.h:64:8: error: unknown type name 'dispenserState_t' 64 | static dispenserState_t upState(dispenser_t *dispenser); | ^~~~~~~~~~~~~~~~ D:/CLionProjects/SIGMA_Embedded/src/motor/motor.h:64:33: error: unknown type name 'dispenser_t' 64 | static dispenserState_t upState(dispenser_t *dispenser); | ^~~~~~~~~~~ D:/CLionProjects/SIGMA_Embedded/src/motor/motor.h:71:8: error: unknown type name 'dispenserState_t' 71 | static dispenserState_t topState(dispenser_t *dispenser); | ^~~~~~~~~~~~~~~~ D:/CLionProjects/SIGMA_Embedded/src/motor/motor.h:71:34: error: unknown type name 'dispenser_t' 71 | static dispenserState_t topState(dispenser_t *dispenser); | ^~~~~~~~~~~
> 
> ..........

Thanks, it's been fixed. It should because of incorrect header file references.

**Comment by DavidFederl** [comment]
I'm not able to build any target except from `left` and `integrationTest-limitSwitches` for the Tiny2040. 
The unit test for the dispenser can also not be build.

---

As far as I read the debug messages all these error are based linkage problems.

**Comment by HuangQing23** [comment]
> I'm not able to build any target except from `left` and `integrationTest-limitSwitches` for the Tiny2040. The unit test for the dispenser can also not be build.
> 
> As far as I read the debug messages all these error are based linkage problems.

Yes because I refactory the code so it will be sth wrong with some functions. The right can be same with left so it's definitely easy. I can fix the rondell and integrationtest_motor and dispenser with their function later so we can build them.

**Pull request merged**
